### ISSUE TITLE
notification about entities that are back to live

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-registry-domain#32] opened 2016-10-27 15:47 UTC
As discussed [here](https://github.com/reTHINK-project/specs/issues/14)

**Comment by rjflp** [comment] 2016-11-16 14:14
One possible way to do this, maintaining the REST interface:

To request notification
- Runtime asks for notification
- Connector transmits the request to the Domain Registry server (REST call)
- DR server associates the url to notify to the object to observe

When there is a change:
- The reply to REST calls will have a flag indicating whether there are any notification pending
- Change is caused by the connector calling a REST resource on the DR. The reply indicates notifications are pending
- The connector calls another REST endpoint on the DR in order to obtain the pending notifications (target and data)
- The connector pushs the messages into the Message Node
- The connector calls the DR (REST API) to inform that the notifications where processed and may be deleted.

**Comment by rjflp** [comment] 2017-02-01 16:39
Status update:
-Methods mostly implemented in the Domain Registry. Still missing database storage.
-Connector still Work In Progress
-Runtime still WIP

**Comment by rjflp** [comment] 2017-03-16 18:28
@pchainho When the runtime receives the notification, from the message node, that the hyperty is back, what should happen?

**Comment by nunofmn** [comment] 2017-03-23 16:46
@pchainho, what do need to implement here from the connector side?
The specs only define a message to the Message Node Subscription Manager.

**Comment by pchainho** [comment] 2017-04-05 20:59
As far as I remember, the connector only has to publish status changes: 

- [When registered entities goes offline publish change to disconnected](https://github.com/reTHINK-project/specs/blob/master/messages/registration-messages.md#publish-registration-object-status-changed-to-disconnected)
- [When registered entities goes online publish change to live](https://github.com/reTHINK-project/specs/blob/master/messages/registration-messages.md#publish-registration-object-status-changed-to-live)

**Comment by nunofmn** [comment] 2017-04-05 21:16
But there is this message also:
https://github.com/reTHINK-project/specs/blob/master/messages/registration-messages.md#subscribe-to-receive-notifications-about-registration-status-changes

Is the Subscription Manager that contacts the Domain Registry directly?

**Comment by pchainho** [comment] 2017-04-05 21:40
No, it is the MN that broadcasts the published status change to all subscribers using pub—sub

**Comment by nunofmn** [comment] 2017-04-24 16:18
In order to this to work is still necessary to implement the "notification" functionality in the Runtime side.
Our proposal of API that should be exposed by the Runtime is simple:
 - `subscribe(<URL_to_subscribe>, <subscriber>, callback)`
 - `unsubscribe(<URL_to_unsubscribe>, <subscriber>)`

From the Runtime <-> Subscription Manager comunication, this will have the following interactions:
 - When the `subscribe` function is called a message is sent from the Runtime to the Subscription Manager (detailed [here](https://github.com/reTHINK-project/specs/blob/master/messages/registration-messages.md#subscribe-to-receive-notifications-about-registration-status-changes)).
 - When a status change is detected the SM will send a message to the Runtimes that asked to be notified. The Runtime then propagates the notification to all the "entities" that subscribed for the change using the `subscribe` function by calling the associated callbacks.

@pchainho seems ok?

**Comment by pchainho** [comment] 2017-04-24 17:57
As discussed in Slack I would propose a more developer friendly API in the service framework discovery lib, where each returned discovered object will support a `onLive()` and a `onDisconnect()` event handler.

**Comment by BernardoMG** [comment] 2017-05-11 14:39
This issue is complete.

The changes are in branch: `hyperty-notification` (service-framework); `disconnected-hyperties` (runtime-core); `connector-release-1.0.0` (msg-node-vertx); `32-connector-sm` (registry-domain).

This issue will be closed after the next release.

**Comment by BernardoMG** [comment] 2017-05-23 18:06
We are replicating the notifications feature to data objects.

**Comment by BernardoMG** [comment] 2017-05-25 18:39
Notification feature is now available not only for hyperties but also for data objects. 

The changes are in branch: `hyperty-notification` (service-framework); `disconnected-hyperties` (runtime-core); `connector-release-1.0.0` (msg-node-vertx); `32-connector-sm` (registry-domain).

This issue will be closed after the next release.

**Comment by pchainho** [comment] 2017-06-21 14:30
I've found some issues when testing with UserAvailability Hyperties at hyperty-notification branch from dev-hyperty repo:

1. when unregistering HypertyAvailabilityReporter, executing `runtime.registry.unregisterAllHyperties();` in the browser console I receive a "not found" response:

![pasted image at 2017_06_21 01_01 pm](https://user-images.githubusercontent.com/3893553/27389058-3c0dcb2a-5695-11e7-953e-3a485b7ea8ef.png)

then, if from HypertyAvailabilityObserver side I try to discover this Hyperty, I got results with "status = live":

![pasted image at 2017_06_21 01_03 pm](https://user-images.githubusercontent.com/3893553/27389499-75dc9b8c-5696-11e7-8f39-4d7da7ba66b4.png)

2.  when the expires is set to 30 sec in the UserAvailabilityReporter Hyperty configuration, and after the UserAvailabilityObserver subscribes the reporter, if I close the windows browser without explicitely unregistering the hyperty (ie sending an update message with status = disconnected), the UserAvailabilityObserver does not receive the `onDisconnect` event when the Hyperty registration expires (after 30 secs)

**Comment by BernardoMG** [comment] 2017-06-22 10:26
Hi @pchainho .

1. The `resource` field is wrong. Should be only: `hyperty://localhost/cc5a34be-d08b-4ff6-a21b-7859690b85b5`. 

2. And that is correct, according to the implementation. The `HeartBeatThread` runs only after one hour. So, unless you make a GET request over the hyperty that validates the expire field, you should wait for the `HeartBeatThread`.

**Comment by BernardoMG** [comment] 2017-09-25 17:47
This issue should be fixed in later versions.

Closing for now.

**Closed by BernardoMG** 2017-09-25 17:47 UTC
Labels: phase 2
